name: local
values:
  - key: keycloak_base_url
    value: 'https://kc.mra.local:9443'
  - key: realm
    value: mra
  - key: client_id
    value: mra-api
  - key: client_secret
    value: mra-api-secret
  - key: base_url
    value: 'https://api.mra.local:8443'
