spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8100/realms/mra/protocol/openid-connect/certs

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4317
management.server.port=9001

application.security.cors.allowed-origins=https://ui.mra.local:8443
application.internal-services.core-service.base-url=http://localhost:8002

logging.structured.format.file=ee.geckosolutions.mra.common.platform.observation.EcsStructuredLogFormatter
logging.file.name=../target/logs/${spring.application.name}.log

server.port=8001