spring.ssl.bundle.pem.server.keystore.certificate=file:../etc/certificate/mra.crt
spring.ssl.bundle.pem.server.keystore.private-key=file:../etc/certificate/mra.key
spring.ssl.bundle.pem.root-ca.truststore.certificate=file:../etc/certificate/root_ca.crt
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://kc.mra.local:9443/realms/mra/protocol/openid-connect/certs

application.internal-services.core-service.base-url=http://localhost:8444

server.ssl.bundle=server
server.port=8443