spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.security.oauth2.resourceserver.jwt.audiences=mra

application.customer.v1-api-deprecated-since=2099-01-01T00:00:00Z
application.security.realm-name=mra

logging.level.org.zalando.logbook=TRACE
