spring.application.name=gateway
spring.security.oauth2.resourceserver.jwt.audiences=mra
spring.mvc.apiversion.use.path-segment=1

application.api.deprecated-endpoints[0].path-template=/api/v1/customers/{id}
application.api.deprecated-endpoints[0].methods=GET
application.api.deprecated-endpoints[0].deprecation-date=2099-01-01T00:00:00Z
application.api.deprecated-endpoints[0].successor-link=/api/v2/customers/{id}
application.api.deprecated-endpoints[1].path-template=/api/v1/customers
application.api.deprecated-endpoints[1].methods=POST,PUT
application.api.deprecated-endpoints[1].deprecation-date=2099-01-01T00:00:00Z
application.api.deprecated-endpoints[1].sunset-date=2099-07-01T00:00:00Z
application.security.realm-name=mra

logging.level.org.zalando.logbook=TRACE
