spring.rabbitmq.host=localhost

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4317
management.server.port=8244

logging.structured.format.file=ee.geckosolutions.mra.common.platform.observation.EcsStructuredLogFormatter
logging.file.name=../target/logs/${spring.application.name}.log

server.port=8444