spring.application.name=token

management.endpoint.health.group.critical.include=redis

logbook.predicate.exclude[0].path=/internal/api/v1/openid-connect/token
logbook.predicate.exclude[0].method=POST

logging.level.org.zalando.logbook=TRACE
