install:
	mvn frontend:npm -Dfrontend.npm.arguments="install --force"

audit-fix:
	mvn frontend:npm -Dfrontend.npm.arguments="audit fix"

start:
	mvn frontend:npm -Dfrontend.npm.arguments="run start"

build:
	mvn frontend:npm -Dfrontend.npm.arguments="run build"

