#!/bin/sh
argv0=$(echo "$0" | sed -e 's,\\,/,g')
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")

case "$(uname -s)" in
  Darwin) basedir="$( cd "$( dirname "$argv0" )" && pwd )";;
  Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
  *MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

command_exists() {
  command -v "$1" >/dev/null 2>&1;
}

if command_exists winpty && test -t 1; then
  winpty "$basedir/target/node/npm.cmd" "$@"
else
  exec "$basedir/target/node/npm" "$@"
fi
ret=$?

exit $ret
